const MOVES_DATABASE = {
  // Normal moves
  tackle: {
    type: "normal",
    category: "physical",
    power: 40,
    accuracy: 100,
    pp: 35,
  },
  scratch: {
    type: "normal",
    category: "physical",
    power: 40,
    accuracy: 100,
    pp: 35,
  },
  pound: {
    type: "normal",
    category: "physical",
    power: 40,
    accuracy: 100,
    pp: 35,
  },
  "body-slam": {
    type: "normal",
    category: "physical",
    power: 85,
    accuracy: 100,
    pp: 15,
  },
  "hyper-beam": {
    type: "normal",
    category: "special",
    power: 150,
    accuracy: 90,
    pp: 5,
  },
  "quick-attack": {
    type: "normal",
    category: "physical",
    power: 40,
    accuracy: 100,
    pp: 30,
    priority: 1,
  },
  slash: {
    type: "normal",
    category: "physical",
    power: 70,
    accuracy: 100,
    pp: 20,
  },
  "mega-punch": {
    type: "normal",
    category: "physical",
    power: 80,
    accuracy: 85,
    pp: 20,
  },
  "mega-kick": {
    type: "normal",
    category: "physical",
    power: 120,
    accuracy: 75,
    pp: 5,
  },
  headbutt: {
    type: "normal",
    category: "physical",
    power: 70,
    accuracy: 100,
    pp: 15,
  },
  uproar: {
    type: "normal",
    category: "special",
    power: 90,
    accuracy: 100,
    pp: 10,
  },

  // Fire moves
  ember: {
    type: "fire",
    category: "special",
    power: 40,
    accuracy: 100,
    pp: 25,
  },
  "fire-punch": {
    type: "fire",
    category: "physical",
    power: 75,
    accuracy: 100,
    pp: 15,
  },
  flamethrower: {
    type: "fire",
    category: "special",
    power: 90,
    accuracy: 100,
    pp: 15,
  },
  "fire-blast": {
    type: "fire",
    category: "special",
    power: 110,
    accuracy: 85,
    pp: 5,
  },
  overheat: {
    type: "fire",
    category: "special",
    power: 130,
    accuracy: 90,
    pp: 5,
    statChanges: { "special-attack": -2, target: "self" },
  },
  "flame-wheel": {
    type: "fire",
    category: "physical",
    power: 60,
    accuracy: 100,
    pp: 25,
  },
  "fire-fang": {
    type: "fire",
    category: "physical",
    power: 65,
    accuracy: 95,
    pp: 15,
  },
  "heat-wave": {
    type: "fire",
    category: "special",
    power: 95,
    accuracy: 90,
    pp: 10,
  },
  "blaze-kick": {
    type: "fire",
    category: "physical",
    power: 85,
    accuracy: 90,
    pp: 10,
  },
  "will-o-wisp": {
    type: "fire", category: "status", power: 0, accuracy: 85, pp: 15,
    statusEffect: { type: "burn", chance: 100 }
  },

  // Water moves
  "water-gun": {
    type: "water",
    category: "special",
    power: 40,
    accuracy: 100,
    pp: 25,
  },
  "bubble-beam": {
    type: "water",
    category: "special",
    power: 65,
    accuracy: 100,
    pp: 20,
  },
  surf: {
    type: "water",
    category: "special",
    power: 90,
    accuracy: 100,
    pp: 15,
  },
  "hydro-pump": {
    type: "water",
    category: "special",
    power: 110,
    accuracy: 80,
    pp: 5,
  },
  "aqua-tail": {
    type: "water",
    category: "physical",
    power: 90,
    accuracy: 90,
    pp: 10,
  },
  waterfall: {
    type: "water",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "aqua-jet": {
    type: "water",
    category: "physical",
    power: 40,
    accuracy: 100,
    pp: 20,
    priority: 1,
  },
  scald: {
    type: "water",
    category: "special",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "steam-eruption": {
    type: "water",
    category: "special",
    power: 110,
    accuracy: 95,
    pp: 5,
  },
  "water-shuriken": {
    type: "water",
    category: "special",
    power: 45,
    accuracy: 100,
    pp: 20,
  },

  // Electric moves
  "thunder-shock": {
    type: "electric",
    category: "special",
    power: 40,
    accuracy: 100,
    pp: 30,
  },
  thunderbolt: {
    type: "electric",
    category: "special",
    power: 90,
    accuracy: 100,
    pp: 15,
  },
  thunder: {
    type: "electric",
    category: "special",
    power: 110,
    accuracy: 70,
    pp: 10,
  },
  "volt-tackle": {
    type: "electric",
    category: "physical",
    power: 120,
    accuracy: 100,
    pp: 15,
  },
  "thunder-punch": {
    type: "electric",
    category: "physical",
    power: 75,
    accuracy: 100,
    pp: 15,
  },
  discharge: {
    type: "electric",
    category: "special",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "wild-charge": {
    type: "electric",
    category: "physical",
    power: 90,
    accuracy: 100,
    pp: 15,
  },

  // Grass moves
  "vine-whip": {
    type: "grass",
    category: "physical",
    power: 45,
    accuracy: 100,
    pp: 25,
  },
  "razor-leaf": {
    type: "grass",
    category: "physical",
    power: 55,
    accuracy: 95,
    pp: 25,
  },
  "solar-beam": {
    type: "grass",
    category: "special",
    power: 120,
    accuracy: 100,
    pp: 10,
  },
  "leaf-blade": {
    type: "grass",
    category: "physical",
    power: 90,
    accuracy: 100,
    pp: 15,
  },
  "energy-ball": {
    type: "grass",
    category: "special",
    power: 90,
    accuracy: 100,
    pp: 10,
  },
  "seed-bomb": {
    type: "grass",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "giga-drain": {
    type: "grass",
    category: "special",
    power: 75,
    accuracy: 100,
    pp: 10,
  },
  "magical-leaf": {
    type: "grass",
    category: "special",
    power: 60,
    accuracy: 999,
    pp: 20,
  },
  "petal-blizzard": {
    type: "grass",
    category: "physical",
    power: 90,
    accuracy: 100,
    pp: 15,
  },

  // Ice moves
  "ice-beam": {
    type: "ice",
    category: "special",
    power: 90,
    accuracy: 100,
    pp: 10,
  },
  blizzard: {
    type: "ice",
    category: "special",
    power: 110,
    accuracy: 70,
    pp: 5,
  },
  "ice-punch": {
    type: "ice",
    category: "physical",
    power: 75,
    accuracy: 100,
    pp: 15,
  },
  "ice-shard": {
    type: "ice",
    category: "physical",
    power: 40,
    accuracy: 100,
    pp: 30,
    priority: 1,
  },
  "frost-breath": {
    type: "ice",
    category: "special",
    power: 60,
    accuracy: 90,
    pp: 10,
  },
  "icicle-crash": {
    type: "ice",
    category: "physical",
    power: 85,
    accuracy: 90,
    pp: 10,
  },

  // Fighting moves
  "karate-chop": {
    type: "fighting",
    category: "physical",
    power: 50,
    accuracy: 100,
    pp: 25,
  },
  "low-kick": {
    type: "fighting",
    category: "physical",
    power: 65,
    accuracy: 100,
    pp: 20,
  },
  "brick-break": {
    type: "fighting",
    category: "physical",
    power: 75,
    accuracy: 100,
    pp: 15,
  },
  "close-combat": {
    type: "fighting",
    category: "physical",
    power: 120,
    accuracy: 100,
    pp: 5,
    statChanges: { defense: -1, "special-defense": -1, target: "self" },
  },
  "focus-blast": {
    type: "fighting",
    category: "special",
    power: 120,
    accuracy: 70,
    pp: 5,
  },
  "mach-punch": {
    type: "fighting",
    category: "physical",
    power: 40,
    accuracy: 100,
    pp: 30,
    priority: 1,
  },
  "cross-chop": {
    type: "fighting",
    category: "physical",
    power: 100,
    accuracy: 80,
    pp: 5,
  },
  "drain-punch": {
    type: "fighting",
    category: "physical",
    power: 75,
    accuracy: 100,
    pp: 10,
  },

  // Psychic moves
  confusion: {
    type: "psychic",
    category: "special",
    power: 50,
    accuracy: 100,
    pp: 25,
  },
  psybeam: {
    type: "psychic",
    category: "special",
    power: 65,
    accuracy: 100,
    pp: 20,
  },
  psychic: {
    type: "psychic",
    category: "special",
    power: 90,
    accuracy: 100,
    pp: 10,
  },
  psyshock: {
    type: "psychic",
    category: "special",
    power: 80,
    accuracy: 100,
    pp: 10,
  },
  "zen-headbutt": {
    type: "psychic",
    category: "physical",
    power: 80,
    accuracy: 90,
    pp: 15,
  },
  extrasensory: {
    type: "psychic",
    category: "special",
    power: 80,
    accuracy: 100,
    pp: 20,
  },

  // Dragon moves
  "dragon-rage": {
    type: "dragon",
    category: "special",
    power: 60,
    accuracy: 100,
    pp: 10,
  },
  "dragon-claw": {
    type: "dragon",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "draco-meteor": {
    type: "dragon",
    category: "special",
    power: 130,
    accuracy: 90,
    pp: 5,
    statChanges: { "special-attack": -2, target: "self" },
  },
  outrage: {
    type: "dragon",
    category: "physical",
    power: 120,
    accuracy: 100,
    pp: 10,
  },
  "dragon-pulse": {
    type: "dragon",
    category: "special",
    power: 85,
    accuracy: 100,
    pp: 10,
  },
  "dragon-rush": {
    type: "dragon",
    category: "physical",
    power: 100,
    accuracy: 75,
    pp: 10,
  },

  // Dark moves
  bite: {
    type: "dark",
    category: "physical",
    power: 60,
    accuracy: 100,
    pp: 25,
  },
  crunch: {
    type: "dark",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "dark-pulse": {
    type: "dark",
    category: "special",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "night-slash": {
    type: "dark",
    category: "physical",
    power: 70,
    accuracy: 100,
    pp: 15,
  },
  "sucker-punch": {
    type: "dark",
    category: "physical",
    power: 70,
    accuracy: 100,
    pp: 5,
    priority: 1,
  },
  "foul-play": {
    type: "dark",
    category: "physical",
    power: 95,
    accuracy: 100,
    pp: 15,
  },
  "beat-up": {
    type: "dark",
    category: "physical",
    power: 10,
    accuracy: 100,
    pp: 10,
  },

  // Ghost moves
  "shadow-ball": {
    type: "ghost",
    category: "special",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "shadow-claw": {
    type: "ghost",
    category: "physical",
    power: 70,
    accuracy: 100,
    pp: 15,
  },
  "shadow-punch": {
    type: "ghost",
    category: "physical",
    power: 60,
    accuracy: 999,
    pp: 20,
  },
  hex: { type: "ghost", category: "special", power: 65, accuracy: 100, pp: 10 },
  "phantom-force": {
    type: "ghost",
    category: "physical",
    power: 90,
    accuracy: 100,
    pp: 10,
  },

  // Steel moves
  "iron-tail": {
    type: "steel",
    category: "physical",
    power: 100,
    accuracy: 75,
    pp: 15,
  },
  "flash-cannon": {
    type: "steel",
    category: "special",
    power: 80,
    accuracy: 100,
    pp: 10,
  },
  "meteor-mash": {
    type: "steel",
    category: "physical",
    power: 90,
    accuracy: 90,
    pp: 10,
  },
  "iron-head": {
    type: "steel",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "steel-wing": {
    type: "steel",
    category: "physical",
    power: 70,
    accuracy: 90,
    pp: 25,
  },

  // Rock moves
  "rock-throw": {
    type: "rock",
    category: "physical",
    power: 50,
    accuracy: 90,
    pp: 15,
  },
  "rock-slide": {
    type: "rock",
    category: "physical",
    power: 75,
    accuracy: 90,
    pp: 10,
  },
  "stone-edge": {
    type: "rock",
    category: "physical",
    power: 100,
    accuracy: 80,
    pp: 5,
  },
  "rock-tomb": {
    type: "rock",
    category: "physical",
    power: 60,
    accuracy: 95,
    pp: 15,
  },
  "power-gem": {
    type: "rock",
    category: "special",
    power: 80,
    accuracy: 100,
    pp: 20,
  },
  "ancient-power": {
    type: "rock",
    category: "special",
    power: 60,
    accuracy: 100,
    pp: 5,
  },

  // Bug moves
  "bug-bite": {
    type: "bug",
    category: "physical",
    power: 60,
    accuracy: 100,
    pp: 20,
  },
  "x-scissor": {
    type: "bug",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 15,
  },
  "signal-beam": {
    type: "bug",
    category: "special",
    power: 75,
    accuracy: 100,
    pp: 15,
  },
  "u-turn": {
    type: "bug",
    category: "physical",
    power: 70,
    accuracy: 100,
    pp: 20,
  },
  megahorn: {
    type: "bug",
    category: "physical",
    power: 120,
    accuracy: 85,
    pp: 10,
  },
  "leech-life": {
    type: "bug",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 10,
  },

  // Fairy moves
  "fairy-wind": {
    type: "fairy",
    category: "special",
    power: 40,
    accuracy: 100,
    pp: 30,
  },
  "dazzling-gleam": {
    type: "fairy",
    category: "special",
    power: 80,
    accuracy: 100,
    pp: 10,
  },
  moonblast: {
    type: "fairy",
    category: "special",
    power: 95,
    accuracy: 100,
    pp: 15,
  },
  "play-rough": {
    type: "fairy",
    category: "physical",
    power: 90,
    accuracy: 90,
    pp: 10,
  },
  "draining-kiss": {
    type: "fairy",
    category: "special",
    power: 50,
    accuracy: 100,
    pp: 10,
  },

  // Flying moves
  peck: {
    type: "flying",
    category: "physical",
    power: 35,
    accuracy: 100,
    pp: 35,
  },
  "aerial-ace": {
    type: "flying",
    category: "physical",
    power: 60,
    accuracy: 999,
    pp: 20,
  },
  "air-slash": {
    type: "flying",
    category: "special",
    power: 75,
    accuracy: 95,
    pp: 15,
  },
  "wing-attack": {
    type: "flying",
    category: "physical",
    power: 60,
    accuracy: 100,
    pp: 35,
  },
  fly: {
    type: "flying",
    category: "physical",
    power: 90,
    accuracy: 95,
    pp: 15,
  },
  "drill-peck": {
    type: "flying",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 20,
  },
  "brave-bird": {
    type: "flying",
    category: "physical",
    power: 120,
    accuracy: 100,
    pp: 15,
  },

  // Ground moves
  "mud-slap": {
    type: "ground",
    category: "special",
    power: 20,
    accuracy: 100,
    pp: 10,
  },
  earthquake: {
    type: "ground",
    category: "physical",
    power: 100,
    accuracy: 100,
    pp: 10,
  },
  "earth-power": {
    type: "ground",
    category: "special",
    power: 90,
    accuracy: 100,
    pp: 10,
  },
  dig: {
    type: "ground",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 10,
  },
  bulldoze: {
    type: "ground",
    category: "physical",
    power: 60,
    accuracy: 100,
    pp: 20,
  },
  "mud-bomb": {
    type: "ground",
    category: "special",
    power: 65,
    accuracy: 85,
    pp: 10,
  },

  // Poison moves
  "poison-sting": {
    type: "poison",
    category: "physical",
    power: 15,
    accuracy: 100,
    pp: 35,
  },
  "sludge-bomb": {
    type: "poison",
    category: "special",
    power: 90,
    accuracy: 100,
    pp: 10,
  },
  "poison-jab": {
    type: "poison",
    category: "physical",
    power: 80,
    accuracy: 100,
    pp: 20,
  },
  "sludge-wave": {
    type: "poison",
    category: "special",
    power: 95,
    accuracy: 100,
    pp: 10,
  },
  acid: {
    type: "poison",
    category: "special",
    power: 40,
    accuracy: 100,
    pp: 30,
  },

  // Status moves
  growl: {
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    pp: 40,
    statChanges: { attack: -1, target: "opponent" },
  },
  "tail-whip": {
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    pp: 30,
    statChanges: { defense: -1, target: "opponent" },
  },
  "swords-dance": {
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 999,
    pp: 20,
    statChanges: { attack: 2, target: "self" },
  },
  "iron-defense": {
    type: "steel",
    category: "status",
    power: 0,
    accuracy: 999,
    pp: 15,
    statChanges: { defense: 2, target: "self" },
  },
  "calm-mind": {
    type: "psychic",
    category: "status",
    power: 0,
    accuracy: 999,
    pp: 20,
    statChanges: { "special-attack": 1, "special-defense": 1, target: "self" },
  },
  "dragon-dance": {
    type: "dragon",
    category: "status",
    power: 0,
    accuracy: 999,
    pp: 20,
    statChanges: { attack: 1, speed: 1, target: "self" },
  },
  "psych-up": {
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    pp: 10,
    statChanges: { "special-attack": 1, defense: 1, target: "self" },
    statusEffect: { type: "burn", chance: 100 },
  },
  leer: {
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    pp: 10,
    statChanges: { defense: -1, target: "opponent" },
  },
};
export default MOVES_DATABASE;
